In [1]:
from pathlib import Path
import pandas as pd

In [2]:
PROJECT_ROOT = Path.cwd().parent
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "credit_risk_dataset.csv"

print(DATA_PATH)
print("File exists:", DATA_PATH.exists())

/Users/marijacolic/PycharmProjects/credit-risk-portfolio-analysis/data/raw/credit_risk_dataset.csv
File exists: True

In [3]:
df = pd.read_csv(DATA_PATH)

In [4]:
clean_df = df.copy()

In [5]:
clean_df["person_emp_length_missing"] = (
    clean_df["person_emp_length"].isna().astype(int)
)

clean_df["person_emp_length"] = clean_df[
    "person_emp_length"
].fillna(clean_df["person_emp_length"].median())

In [6]:
clean_df["loan_int_rate_missing"] = (
    clean_df["loan_int_rate"].isna().astype(int)
)

median_rate_by_grade = clean_df.groupby(
    "loan_grade"
)["loan_int_rate"].transform("median")

clean_df["loan_int_rate"] = clean_df[
    "loan_int_rate"
].fillna(median_rate_by_grade)

In [7]:
clean_df["person_age"].describe()

count    32581.000000
mean        27.734600
std          6.348078
min         20.000000
25%         23.000000
50%         26.000000
75%         30.000000
max        144.000000
Name: person_age, dtype: float64

In [8]:
clean_df.sort_values(
    "person_age",
    ascending=False
)[["person_age", "person_income"]].head(20)

       person_age  person_income
81            144         250000
183           144         200000
32297         144        6000000
575           123          80004
747           123          78000
32416          94          24000
32506          84          94800
32422          80          64000
32355          78          48000
32534          76          75000
32432          73          75000
32381          73          42000
32521          73          39240
32522          70          48000
32532          70         132000
32360          70          39996
32383          70          30000
32436          70          42000
32334          70          30000
32385          70          44000

In [9]:
clean_df[
    clean_df["person_emp_length"] >
    clean_df["person_age"] - 14
][
    ["person_age", "person_emp_length"]
].head(20)

     person_age  person_emp_length
0            22              123.0
210          21              123.0

In [10]:
clean_df["person_income"].quantile(
    [0, 0.01, 0.25, 0.5, 0.75, 0.99, 1]
)

0.00       4000.0
0.01      14400.0
0.25      38500.0
0.50      55000.0
0.75      79200.0
0.99     225200.0
1.00    6000000.0
Name: person_income, dtype: float64

In [11]:
categorical_columns = [
    "person_home_ownership",
    "loan_intent",
    "loan_grade",
    "cb_person_default_on_file"
]

for column in categorical_columns:
    print(f"\nColumn: {column}")
    print(clean_df[column].value_counts(dropna=False))

Column: person_home_ownership
person_home_ownership
RENT        16446
MORTGAGE    13444
OWN          2584
OTHER         107
Name: count, dtype: int64

Column: loan_intent
loan_intent
EDUCATION            6453
MEDICAL              6071
VENTURE              5719
PERSONAL             5521
DEBTCONSOLIDATION    5212
HOMEIMPROVEMENT      3605
Name: count, dtype: int64

Column: loan_grade
loan_grade
A    10777
B    10451
C     6458
D     3626
E      964
F      241
G       64
Name: count, dtype: int64

Column: cb_person_default_on_file
cb_person_default_on_file
N    26836
Y     5745
Name: count, dtype: int64

In [12]:
OUTPUT_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "credit_risk_clean.csv"
)

clean_df.to_csv(OUTPUT_PATH, index=False)

print("Saved cleaned dataset to:", OUTPUT_PATH)

Saved cleaned dataset to: /Users/marijacolic/PycharmProjects/credit-risk-portfolio-analysis/data/processed/credit_risk_clean.csv